# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'StarterApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarterApp
  plugin 'cocoapods-keys', {
      :project => "StarterApp",
      :target => "StarterApp",
      :keys => [
      "MarvelApiKey",
      "MarvelPrivateKey"
      ]}
pod 'SteviaLayout'
pod 'AnimatedCollectionViewLayout'
pod "ViewAnimator"
pod 'ws'
pod 'CryptoSwift'
pod 'Kingfisher'
pod 'Hero'
end
